### ISSUE TITLE
Issue when interpolating quarterly data from a monthly data through chow-lin method

### ISSUE THREAD

**Issue by steveshaoucsb** [jessegrabowski/tsdisagg#2] opened 2024-08-06 11:29 UTC
I was trying to use your package to conduct interpolation of quarterly data from monthly data through the Chow-lin method. In the function "handle_endpoint_differences(low_freq_df, high_freq_df)", because it uses "getattr" function from pandas, it will always generates C_mask with the length of 4 as low_freq_index goes:1, 2, 3, 4, and high_freq_index goes 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, etc., letting full_set in the handle_endpoint_difference becomes just [1, 2, 3, 4]. Because of this, it always leads to this error:

--> [348](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/lib/python3.11/site-packages/tsdisagg/ts_disagg.py:348) C = build_conversion_matrix(n, nl, time_conversion_factor, agg_func=agg_func, C_mask=C_mask)
...
---> [41](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/lib/python3.11/site-packages/tsdisagg/ts_disagg.py:41) C = C[C_mask, :n]
     [44](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/lib/python3.11/site-packages/tsdisagg/ts_disagg.py:44) return C

IndexError: boolean index did not match indexed array along dimension 0; dimension is 21 but corresponding boolean dimension is 4

**Comment by jessegrabowski** [comment] 2024-08-06 11:43
Thanks for reporting! I'll take a look and patch as soon as I can. PR also welcome if you can't wait, seems like you understand where the issue is?

**Comment by steveshaoucsb** [comment] 2024-08-06 12:02
Yes! I will make my pull request now with my fix! Not completely sure whether it is 100% correct but it works!

**Comment by jessegrabowski** [comment] 2024-08-08 05:56
Closed by #4 

This should be fixed, and I released a patch on pypi, so you can `pip install tsdisagg==1.2.0` to get the fix. Let me know if you still hit problems. Thanks again for working on this!

**Closed as completed by jessegrabowski** 2024-08-08 05:56 UTC
